# Generated by Django 5.0.6 on 2024-09-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_logged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_logged',
        ),
    ]
